[workspace]
members = [
    "feature/chunk",
    "feature/generic-assert",
    "main",
]

[workspace.dependencies]
bevy = "0.11"  # Основной графический движок
bevy_math = "0.11"  # Математические операции
rand = "0.8.5" # Генерация случайных чисел

[profile.dev.package."*"]
opt-level = 3